spring:
  application:
    name: fluxgate

# wireMock 설정
client:
  user-service:
    base-url: http://localhost:8081
  order-service:
    base-url: http://localhost:8081
  notification-service:
    base-url: http://localhost:8081

# 모니터링 설정
management:
  endpoints:
    web:
      base-path: /
      exposure:
        include: health,prometheus
  endpoint:
    prometheus:
      enabled: true

